import Head from 'next/head'
// import { Inter } from 'next/font/google'
import Link from 'next/link'
import { useState } from 'react'
import Image from 'next/image'
import sterlingLogo from '../images/sterlingLogo.png'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');

  const handleEmail = (event) => {
    setEmail(event.target.value);
  };
  const handlePass = (event) => {
    setPassword(event.target.value);
  };
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='flex h-screen justify-center items-center relative bg-container'>
        <div className='absolute top-0 left-0 p-2 text-bold text-xl text-white w-[60px]'><Image src={sterlingLogo} alt='sterling logo'/></div>
        <div className='bg-white flex flex-col w-full mx-2 items-center justify-center font-sans font-semibold container border rounded-2xl py-4 drop-shadow-2xl max-w-[400px]'>
          <h1 className='text-2xl mt-4 mb-6 text-blue-950'>Login</h1>
          <form className='flex flex-col w-full p-3'>
          <div className='mt-2 mb-4 relative'>
              <input 
              type="text" 
              id="email"
              value={email}
              onChange={handleEmail} className="w-full border border-gray-500 focus:border-red-600 text-gray-500 bg-transparent py-2 pl-1.5 outline-none rounded-lg py-2 my-1 px-2"/>
              <label className={`${
                email ? '-top-5 left-1 text-sm text-red-500' : 'text-gray-500 top-3 left-1.5'
                } absolute left-3 transition-all duration-200 `}
                htmlFor="exampleFormControlInput1">
                  Email
              </label>
            </div>
            <div className='my-2 relative'>
              
              <input 
              type="password" 
              id="password"
              value={password}
              onChange={handlePass} className="w-full border border-gray-500 text-gray-500 focus:border-red-600 bg-transparent py-2 pl-1.5 outline-none rounded-lg py-2 my-1 px-2"/>
              <label className={`${
                password ? '-top-5 left-1 text-sm text-red-500' : 'text-gray-500 top-3 left-1.5'
                } absolute left-3 transition-all duration-200 `}
                htmlFor="exampleFormControlInput1">
                  Password
              </label>
            </div>
            <Link href='/navigate'>
              <button className='w-full bg-red-600 hover:bg-red-800 text-white rounded-md p-3 my-4'>login</button>
            </Link>
          </form>
        </div>
      </main>
    </>
  )
}
